### ISSUE TITLE
Branch cleanup: daterange

### ISSUE THREAD

**Issue by KatiRG** [ongov/ckanext-ontario_theme#224]
There are some outstanding low-priority date display features that were completed before the upgrade that can be merged if desired:

New features in branch `daterange`:
- displays "Single-day snapshot: yyyy-mm-dd" when dataset date range spans only one day
- displays "YYYY-MM" when dataset date range spans one month entirely

**Comment by KatiRG** [comment]
- for datasets spanning only one day, the catalogue currently shows ([example](https://data.ontario.ca/dataset/private-school-contact-information)):
<img width="375" alt="Screen Shot 2022-10-26 at 1 14 11 PM" src="https://user-images.githubusercontent.com/1254764/198092574-13a06f1c-d1a5-4d5c-a3c3-6014bb4dba68.png">

=> Propose to replace this date range label by a label that shows: "**Single-day snapshot: 2022-10-07**" 


- for datasets spanning one entire month, the catalogue currently shows ([example](https://data.ontario.ca/dataset/the-ontario-wildlife-damage-compensation-program-fair-market-value-valuation-table)) :

<img width="319" alt="Screen Shot 2022-10-26 at 1 17 13 PM" src="https://user-images.githubusercontent.com/1254764/198093119-329428d8-40e8-43ac-9490-a91499bac4ac.png">

=> Propose to replace this date range label by a label that shows: "**2022-10**"

**Comment by pattyfacy** [comment]
Agreed with the changes, but can we also change format to Month Day, Year (October 7, 2022) / Month Year (October 2022) to follow the [style guide?](https://www.ontario.ca/page/ontarioca-style-guide)

**Comment by KatiRG** [comment]
Finalized date ranges implemented in https://github.com/ongov/ckanext-ontario_theme/pull/357
